apiVersion: litmuchaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  name: generic
spec:
  displayName: genericchaos
  experiments:
  - container-kill
  - disk-fill
  - docker-service-kill
  - kubelet-service-kill
  - pod-network-corruption
  - pod-network-duplication
  - pod-network-latency
  - pod-network-duplication
